// <auto-generated />
using System;
using CapstoneProjectRegistration.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapstoneProjectRegistration.Repositories.Migrations
{
    [DbContext(typeof(CapstoneDbContext))]
    [Migration("20260423173904_IdentityAuthRestAndSeed")]
    partial class IdentityAuthRestAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            Name = "System Admin",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("Lecture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lecturer1@gmail.com",
                            Name = "Lecturer 1",
                            Phone = "0900000001",
                            Specialization = "Software Engineering",
                            Status = "Active",
                            Title = "Dr"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lecturer2@gmail.com",
                            Name = "Lecturer 2",
                            Phone = "0900000002",
                            Specialization = "Information Systems",
                            Status = "Active",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lecturer3@gmail.com",
                            Name = "Lecturer 3",
                            Phone = "0900000003",
                            Specialization = "AI",
                            Status = "Active",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 4,
                            Email = "lecturer4@gmail.com",
                            Name = "Lecturer 4",
                            Phone = "0900000004",
                            Specialization = "Data Science",
                            Status = "Active",
                            Title = "Prof"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.RegistrationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("RegistrationPeriod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring 2026 - Week 1",
                            SemesterId = 1,
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring 2026 - Week 2",
                            SemesterId = 1,
                            StartDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring 2026 - Week 3",
                            SemesterId = 1,
                            StartDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring 2026 - Week 4",
                            SemesterId = 1,
                            StartDate = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring 2026 - Final intake",
                            SemesterId = 1,
                            StartDate = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Semester");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring 2026",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GroupRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "thinhpdqse171589@fpt.edu.vn",
                            GroupRole = "Leader",
                            Name = "Pham Dinh Quoc Thinh",
                            Phone = "0842918005",
                            Status = "Active",
                            StudentCode = "SE171589"
                        },
                        new
                        {
                            Id = 2,
                            Email = "namnnse182539@fpt.edu.vn",
                            GroupRole = "Member",
                            Name = "Nguyen Nhat Nam",
                            Phone = "0704656071",
                            Status = "Active",
                            StudentCode = "SE182539"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PublicStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RegistrationPeriodId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VietnameseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RegistrationPeriodId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("TopicCode")
                        .IsUnique();

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CreatedAt = new DateTime(2026, 4, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            Description = "Learning system for bone diseases.",
                            EnglishName = "BoneVisQA Interactive Learning",
                            PublicStatus = "Public",
                            RegistrationPeriodId = 1,
                            ReviewStatus = "Approved",
                            SemesterId = 1,
                            Status = "Approved",
                            TopicCode = "SU26SE0011",
                            VietnameseName = "BoneVisQA Hỏi Đáp Trực Quan"
                        },
                        new
                        {
                            Id = 1002,
                            CreatedAt = new DateTime(2026, 4, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 4,
                            Description = "Detect duplicated project ideas via fuzzy matching and semantic scoring.",
                            EnglishName = "Capstone Topic Similarity Scanner",
                            PublicStatus = "Private",
                            RegistrationPeriodId = 1,
                            ReviewStatus = "Rejected",
                            SemesterId = 1,
                            Status = "Rejected",
                            TopicCode = "SU26SE002",
                            VietnameseName = "Hệ thống số khớp đề tài do an"
                        },
                        new
                        {
                            Id = 1003,
                            CreatedAt = new DateTime(2026, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 2,
                            Description = "Mobile-first booking flow with conflict detection and notifications.",
                            EnglishName = "Campus Room Booking Assistant",
                            PublicStatus = "Private",
                            RegistrationPeriodId = 2,
                            ReviewStatus = "Pending",
                            SemesterId = 1,
                            Status = "Pending",
                            TopicCode = "SU26SE003",
                            VietnameseName = "Trợ lý đặt phòng học trong campus"
                        },
                        new
                        {
                            Id = 1004,
                            CreatedAt = new DateTime(2026, 4, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 3,
                            Description = "Dashboard for students and staff to track graduation requirements.",
                            EnglishName = "Graduation Checklist Tracker",
                            PublicStatus = "Public",
                            RegistrationPeriodId = 2,
                            ReviewStatus = "Approved",
                            SemesterId = 1,
                            Status = "Approved",
                            TopicCode = "SU26SE004",
                            VietnameseName = "Theo dõi checklist tốt nghiệp"
                        },
                        new
                        {
                            Id = 1005,
                            CreatedAt = new DateTime(2026, 4, 16, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            Description = "Collect Git-based metrics and visualize review quality over sprints.",
                            EnglishName = "Peer Code Review Metrics",
                            PublicStatus = "Private",
                            RegistrationPeriodId = 3,
                            ReviewStatus = "Pending",
                            SemesterId = 1,
                            Status = "Draft",
                            TopicCode = "SU26SE005",
                            VietnameseName = "Đo lường peer code review"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.TopicReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TopicId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("TopicReview");

                    b.HasData(
                        new
                        {
                            Id = 5001,
                            Comment = "Clear scope.",
                            Decision = "Approved",
                            IsFinalized = true,
                            ReviewDate = new DateTime(2026, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerId = 2,
                            TopicId = 1001
                        },
                        new
                        {
                            Id = 5002,
                            Comment = "Good practical value.",
                            Decision = "Approved",
                            IsFinalized = true,
                            ReviewDate = new DateTime(2026, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerId = 3,
                            TopicId = 1001
                        },
                        new
                        {
                            Id = 5003,
                            Comment = "Topic overlaps too much with existing works.",
                            Decision = "Rejected",
                            IsFinalized = true,
                            ReviewDate = new DateTime(2026, 4, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerId = 2,
                            TopicId = 1002
                        },
                        new
                        {
                            Id = 5004,
                            Comment = "Acceptable but revise objectives.",
                            Decision = "Approved",
                            IsFinalized = true,
                            ReviewDate = new DateTime(2026, 4, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerId = 3,
                            TopicId = 1002
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Admin", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Lecturer", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.RegistrationPeriod", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Semester", "Semester")
                        .WithMany("RegistrationPeriods")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Student", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Topic", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Lecturer", "Creator")
                        .WithMany("Topics")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.RegistrationPeriod", "RegistrationPeriod")
                        .WithMany("Topics")
                        .HasForeignKey("RegistrationPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Semester", "Semester")
                        .WithMany("Topics")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("RegistrationPeriod");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.TopicReview", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Lecturer", "Reviewer")
                        .WithMany("TopicReviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Topic", "Topic")
                        .WithMany("TopicReviews")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Lecturer", b =>
                {
                    b.Navigation("TopicReviews");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.RegistrationPeriod", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Semester", b =>
                {
                    b.Navigation("RegistrationPeriods");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Topic", b =>
                {
                    b.Navigation("TopicReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
