// <auto-generated />
using System;
using CapstoneProjectRegistration.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapstoneProjectRegistration.Repositories.Migrations
{
    [DbContext(typeof(CapstoneDbContext))]
    [Migration("20260416173746_DemoSeedDataPack")]
    partial class DemoSeedDataPack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@capstone.local",
                            Name = "System Admin",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Lecture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lecturer.a@example.com",
                            Name = "Nguyen Van A",
                            Phone = "0900000001",
                            Specialization = "Software Engineering",
                            Status = "Active",
                            Title = "Dr"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lecturer.b@example.com",
                            Name = "Tran Thi B",
                            Phone = "0900000002",
                            Specialization = "Information Systems",
                            Status = "Active",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lecturer.c@example.com",
                            Name = "Le Van C",
                            Phone = "0900000003",
                            Specialization = "AI",
                            Status = "Active",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 4,
                            Email = "lecturer.d@example.com",
                            Name = "Pham Thi D",
                            Phone = "0900000004",
                            Specialization = "Data Science",
                            Status = "Active",
                            Title = "Prof"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.RegistrationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("RegistrationPeriod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring 2026",
                            SemesterId = 1,
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer 2026",
                            SemesterId = 1,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Semester");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring 2026",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GroupRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "thinhpdqse171589@fpt.edu.vn",
                            GroupRole = "Leader",
                            Name = "Pham Dinh Quoc Thinh",
                            Phone = "0842918005",
                            Status = "Active",
                            StudentCode = "SE171589"
                        },
                        new
                        {
                            Id = 2,
                            Email = "namnnse182539@fpt.edu.vn",
                            GroupRole = "Member",
                            Name = "Nguyen Nhat Nam",
                            Phone = "0704656071",
                            Status = "Active",
                            StudentCode = "SE182539"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PublicStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RegistrationPeriodId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VietnameseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RegistrationPeriodId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("TopicCode")
                        .IsUnique();

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CreatedAt = new DateTime(2026, 4, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1,
                            Description = "Interactive VQA and RAG based learning system for bone diseases.",
                            EnglishName = "BoneVisQA Interactive Learning",
                            PublicStatus = "Public",
                            RegistrationPeriodId = 1,
                            ReviewStatus = "Approved",
                            SemesterId = 1,
                            Status = "Approved",
                            TopicCode = "SP26SE110",
                            VietnameseName = "BoneVisQA Hoi Dap Truc Quan"
                        },
                        new
                        {
                            Id = 1002,
                            CreatedAt = new DateTime(2026, 4, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 4,
                            Description = "Detect duplicated project ideas via fuzzy matching and semantic scoring.",
                            EnglishName = "Capstone Topic Similarity Scanner",
                            PublicStatus = "Private",
                            RegistrationPeriodId = 1,
                            ReviewStatus = "Rejected",
                            SemesterId = 1,
                            Status = "Rejected",
                            TopicCode = "SU26SE002",
                            VietnameseName = "He thong so khop de tai do an"
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.TopicReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TopicId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("TopicReview");

                    b.HasData(
                        new
                        {
                            Id = 5001,
                            Comment = "Clear scope.",
                            Decision = "Approved",
                            IsFinalized = true,
                            ReviewDate = new DateTime(2026, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerId = 2,
                            TopicId = 1001
                        },
                        new
                        {
                            Id = 5002,
                            Comment = "Good practical value.",
                            Decision = "Approved",
                            IsFinalized = true,
                            ReviewDate = new DateTime(2026, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerId = 3,
                            TopicId = 1001
                        },
                        new
                        {
                            Id = 5003,
                            Comment = "Topic overlaps too much with existing works.",
                            Decision = "Rejected",
                            IsFinalized = true,
                            ReviewDate = new DateTime(2026, 4, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerId = 2,
                            TopicId = 1002
                        },
                        new
                        {
                            Id = 5004,
                            Comment = "Acceptable but revise objectives.",
                            Decision = "Approved",
                            IsFinalized = true,
                            ReviewDate = new DateTime(2026, 4, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerId = 3,
                            TopicId = 1002
                        });
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.RegistrationPeriod", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Semester", "Semester")
                        .WithMany("RegistrationPeriods")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Topic", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Lecturer", "Creator")
                        .WithMany("Topics")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.RegistrationPeriod", "RegistrationPeriod")
                        .WithMany("Topics")
                        .HasForeignKey("RegistrationPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Semester", "Semester")
                        .WithMany("Topics")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("RegistrationPeriod");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.TopicReview", b =>
                {
                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Lecturer", "Reviewer")
                        .WithMany("TopicReviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapstoneProjectRegistration.Repositories.Entities.Topic", "Topic")
                        .WithMany("TopicReviews")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Lecturer", b =>
                {
                    b.Navigation("TopicReviews");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.RegistrationPeriod", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Semester", b =>
                {
                    b.Navigation("RegistrationPeriods");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("CapstoneProjectRegistration.Repositories.Entities.Topic", b =>
                {
                    b.Navigation("TopicReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
